name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'
    - uses: actions/cache@v1
      with:
        path: ${{ matrix.flutter_path }}
        key: ${{ runner.os }}-flutter-install-cache-${{ env.flutter_version }}
    - run: flutter pub get
    - run: flutter build apk
